qingfeng-interface/src/main/java/com/qingfeng/framework/monitor/entity/Jvm.java
package com.qingfeng.framework.monitor.entity;

import com.qingfeng.util.CalculationUtil;
import com.qingfeng.util.DateTimeUtil;
import lombok.Data;

import java.io.Serializable;
import java.lang.management.ManagementFactory;
import java.util.Date;

@Data
public class Jvm implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 当前JVM占用的内存总数(M)
     */
    private double total;

    /**
     * JVM最大可用内存总数(M)
     */
    private double max;

    /**
     * JVM空闲内存(M)
     */
    private double free;

    /**
     * JDK版本
     */
    private String version;

    /**
     * JDK路径
     */
    private String home;

    public double getTotal() {
        String value = "";
        try {
            value = CalculationUtil.divide(total+"", (1024 * 1024)+"", 2);
        }catch (Exception e){
            e.printStackTrace();
        }
        return Double.parseDouble(value);
    }

    public double getMax() {
        String value = "";
        try {
            value = CalculationUtil.divide(max+"", (1024 * 1024)+"", 2);
        }catch (Exception e){
            e.printStackTrace();
        }
        return Double.parseDouble(value);
    }

    public double getFree() {
        String value = "";
        try {
            value = CalculationUtil.divide(free+"", (1024 * 1024)+"", 2);
        }catch (Exception e){
            e.printStackTrace();
        }
        return Double.parseDouble(value);
    }

    public double getUsed() {
        String value = "";
        try {
            value = CalculationUtil.divide((total - free)+"", (1024 * 1024)+"", 2);
        }catch (Exception e){
            e.printStackTrace();
        }
        return Double.parseDouble(value);
    }

    public String getVersion() {
        return version;
    }

    public String getHome() {
        return home;
    }

    public double getUsage() {
        String value = "";
        try {
            value = CalculationUtil.multiply(CalculationUtil.divide((total - free)+"", total+"", 4), "100",2);
        }catch (Exception e){
            e.printStackTrace();
        }
        return Double.parseDouble(value);
    }
    /**
     * 获取JDK名称
     */
    public String getName() {
        return ManagementFactory.getRuntimeMXBean().getVmName();
    }

    /**
     * JDK启动时间
     */
    public String getStartTime() {
        long time = ManagementFactory.getRuntimeMXBean().getStartTime();
        Date date = new Date(time);
        String value = "";
        try {
            value = DateTimeUtil.getDateTimeStr(date);
        }catch (Exception e){
            e.printStackTrace();
        }
        return value;
    }

    /**
     * JDK运行时间
     */
    public String getRunTime() {
        long time = ManagementFactory.getRuntimeMXBean().getStartTime();
        String value = "";
        try {
            value = DateTimeUtil.getDatePoor(new Date(time), DateTimeUtil.getDateTime());
        }catch (Exception e){
            e.printStackTrace();
        }
        return value;
    }
}

qingfeng-interface/src/main/java/com/qingfeng/gencode/controller/MycontentController.java
package com.qingfeng.gencode.controller;

import com.qingfeng.base.controller.BaseController;
import com.qingfeng.common.service.UploadService;
import com.qingfeng.framework.jwt.util.JwtUtils;
import com.qingfeng.gencode.service.MycontentService;
import com.qingfeng.system.service.UserService;
import com.qingfeng.util.*;
import com.qingfeng.util.upload.ParaUtil;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletResponse;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * @Title: MycontentController
 * @ProjectName com.qingfeng
 * @Description: Controller层
 * @author anxingtao
 * @date 2020-9-22 22:45
 */
@Controller
@RequestMapping(value = "/gencode/mycontent")
public class MycontentController extends BaseController {

	@Autowired
	private MycontentService mycontentService;
	@Autowired
	public UploadService uploadService;
	@Autowired
	private UserService userService;


	/** 
	 * @Description: findListPage 
	 * @Param: [page, request, response, session] 
	 * @return: void 
	 * @Author: anxingtao
	 * @Date: 2020-9-22 22:51 
	 */
	@RequestMapping(value = "/findListPage", method = RequestMethod.POST)
	public void findListPage(@RequestHeader HttpHeaders headers, @RequestBody PageData pd, HttpServletResponse response) throws IOException {
		Page page = new Page();
		//处理数据权限
		String  token = headers.get("access-token").get(0);
		String user_id = JwtUtils.validateJWT(token).getClaims().getId().split(":")[0];
		String organize_id = JwtUtils.validateJWT(token).getClaims().getId().split(":")[1];
		pd.put("auth_user",user_id);
		pd.put("auth_organize",organize_id);
		pd.put("user_id",user_id);
		PageData orgPd = userService.findUserOrganizeInfo(pd);
		if(Verify.verifyIsNotNull(orgPd.get("authOrgIds"))){
			pd.put("auth_organize_ids",Arrays.asList(orgPd.get("authOrgIds").toString().split(",")));
		}else{
			pd.put("auth_organize_ids",new ArrayList<String>());
		}
		//处理分页
		if(Verify.verifyIsNotNull(pd.get("page"))){
		page.setIndex(Integer.parseInt(pd.get("page").toString()));
		}else{
		page.setIndex(1);
		}
		if(Verify.verifyIsNotNull(pd.get("limit"))){
		page.setShowCount(Integer.parseInt(pd.get("limit").toString()));
		}else{
		page.setShowCount(10);
		}
		page.setPd(pd);
		List<PageData> list = mycontentService.findListPage(page);
		for(PageData p:list){
			//查询简介附件信息
			PageData filePd = new PageData();
			filePd.put("idList",Arrays.asList(p.get("intro").toString().split(",")));
			List<PageData> introFileList = uploadService.findFileList(filePd);
			p.put("introFileList",introFileList);
		}
		int num = mycontentService.findListSize(page);
		Json json = new Json();
		json.setMsg("获取数据成功。");
		json.setCount(num);
		json.setData(list);
		json.setSuccess(true);
		this.writeJson(response,json);
	}

    /** 
     * @Description: findList 
     * @Param: [request, response] 
     * @return: void 
     * @Author: anxingtao
     * @Date: 2020-9-22 22:51 
     */
        @RequestMapping(value = "/findList", method = RequestMethod.POST)
        public void findList(@RequestHeader HttpHeaders headers,@RequestBody PageData pd, HttpServletResponse response) throws IOException  {
    	List<PageData> list = mycontentService.findList(pd);
        Json json = new Json();
        json.setMsg("获取数据成功。");
        json.setData(list);
        json.setSuccess(true);
        this.writeJson(response,json);
    }

	/** 
	 * @Description: save 
	 * @Param: [request, response, session] 
	 * @return: void 
	 * @Author: anxingtao
	 * @Date: 2020-9-22 22:51 
	 */
	@RequestMapping(value = "/saveOrUpdate", method = RequestMethod.POST)
	public void save(@RequestHeader HttpHeaders headers, @RequestBody PageData pd, HttpServletResponse response) throws IOException  {
		Json json = new Json();
		//处理数据权限
		String  token = headers.get("access-token").get(0);
		System.out.println("findUserInfo###########TOKEN:"+token);
		String user_id = JwtUtils.validateJWT(token).getClaims().getId().split(":")[0];
		String organize_id = JwtUtils.validateJWT(token).getClaims().getId().split(":")[1];
		String time = DateTimeUtil.getDateTimeStr();
        if(Verify.verifyIsNotNull(pd.get("id"))){
            pd.put("update_time", time);
            pd.put("update_user",user_id);
            int num = mycontentService.update(pd);
            if(num==1){
                    //处理简介附件信息-更新信息主要意义在于可删选删除垃圾图片
                    PageData filePd = new PageData();
                    filePd.put("obj_id",pd.get("id"));
                    filePd.put("update_time", time);
                    filePd.put("update_user", user_id);
                    String file_intro[] = pd.get("intro").toString().split(",");
                    for (String file_intro_id:file_intro) {
                    filePd.put("id", file_intro_id);
                    uploadService.updateFile(filePd);
                    }
            }
            json.setSuccess(true);
            json.setMsg("操作成功。");
		}else{
            //主键id
            String id = GuidUtil.getUuid();
            pd.put("id", id);
            pd.put("create_time", time);
            pd.put("status","1");
            //处理数据权限
            pd.put("create_user",user_id);
            pd.put("create_organize",organize_id);

            int num = mycontentService.save(pd);
            if(num==1){
                    //处理简介附件信息-更新信息主要意义在于可删选删除垃圾图片
                    PageData filePd = new PageData();
                    filePd.put("obj_id",id);
                    filePd.put("update_time", time);
                    filePd.put("update_user", user_id);
                    String file_intro[] = pd.get("intro").toString().split(",");
                    for (String file_intro_id:file_intro) {
                    filePd.put("id", file_intro_id);
                    uploadService.updateFile(filePd);
                    }
            }
            json.setSuccess(true);
            json.setMsg("操作成功。");
		}
		this.writeJson(response,json);
	}


	/**
	 * @Description: del 
	 * @Param: [request, response] 
	 * @return: void 
	 * @Author: anxingtao
	 * @Date: 2020-9-22 22:51 
	 */
	@RequestMapping(value = "/del", method = RequestMethod.GET)
	public void del(@RequestHeader HttpHeaders headers, @RequestParam String ids, HttpServletResponse response) throws IOException  {
		PageData pd = new PageData();
		String[] del_ids = ids.split(",");
        //删除主表附件信息
        for (String id:del_ids) {
			pd.put("obj_id",id);
			List<PageData> fileList = uploadService.findFileList(pd);
			for (PageData fPd:fileList) {
				//查询信息
				File pathFile = new File(ParaUtil.localName+fPd.getString("file_path"));
				pathFile.delete();
				pathFile.deleteOnExit();
				uploadService.delFile(fPd);
			}
        }
		mycontentService.del(del_ids);
		Json json = new Json();
		json.setSuccess(true);
		json.setMsg("操作成功。");
		this.writeJson(response,json);
	}

}

qingfeng-interface/src/main/java/com/qingfeng/gencode/controller/MytreeController.java
package com.qingfeng.gencode.controller;

import com.qingfeng.base.controller.BaseController;
import com.qingfeng.common.service.UploadService;
import com.qingfeng.framework.jwt.util.JwtUtils;
import com.qingfeng.gencode.service.MytreeService;
import com.qingfeng.system.service.UserService;
import com.qingfeng.util.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * @Title: MytreeController
 * @ProjectName com.qingfeng
 * @Description: Controller层
 * @author anxingtao
 * @date 2020-9-22 22:45
 */
@Controller
@RequestMapping(value = "/gencode/mytree")
public class MytreeController extends BaseController {

	@Autowired
	private MytreeService mytreeService;
	@Autowired
	public UploadService uploadService;
	@Autowired
	private UserService userService;


	/** 
	 * @Description: findListPage 
	 * @Param: [page, request, response, session] 
	 * @return: void 
	 * @Author: anxingtao
	 * @Date: 2020-9-22 22:51 
	 */
	@RequestMapping(value = "/findListPage", method = RequestMethod.POST)
	public void findListPage(@RequestHeader HttpHeaders headers, @RequestBody PageData pd, HttpServletResponse response) throws IOException {
		Page page = new Page();
		//处理数据权限
		String  token = headers.get("access-token").get(0);
		String user_id = JwtUtils.validateJWT(token).getClaims().getId().split(":")[0];
		String organize_id = JwtUtils.validateJWT(token).getClaims().getId().split(":")[1];
		pd.put("auth_user",user_id);
		pd.put("auth_organize",organize_id);
		pd.put("user_id",user_id);
		PageData orgPd = userService.findUserOrganizeInfo(pd);
		if(Verify.verifyIsNotNull(orgPd.get("authOrgIds"))){
			pd.put("auth_organize_ids",Arrays.asList(orgPd.get("authOrgIds").toString().split(",")));
		}else{
			pd.put("auth_organize_ids",new ArrayList<String>());
		}
		//处理分页
		if(Verify.verifyIsNotNull(pd.get("page"))){
		page.setIndex(Integer.parseInt(pd.get("page").toString()));
		}else{
		page.setIndex(1);
		}
		if(Verify.verifyIsNotNull(pd.get("limit"))){
		page.setShowCount(Integer.parseInt(pd.get("limit").toString()));
		}else{
		page.setShowCount(10);
		}
		page.setPd(pd);
		List<PageData> list = mytreeService.findListPage(page);
		for(PageData p:list){
		}
		int num = mytreeService.findListSize(page);
		Json json = new Json();
		json.setMsg("获取数据成功。");
		json.setCount(num);
		json.setData(list);
		json.setSuccess(true);
		this.writeJson(response,json);
	}

    /** 
     * @Description: findList 
     * @Param: [request, response] 
     * @return: void 
     * @Author: anxingtao
     * @Date: 2020-9-22 22:51 
     */
        @RequestMapping(value = "/findList", method = RequestMethod.POST)
        public void findList(@RequestHeader HttpHeaders headers,@RequestBody PageData pd, HttpServletResponse response) throws IOException  {
    	List<PageData> list = mytreeService.findList(pd);
        Json json = new Json();
        json.setMsg("获取数据成功。");
        json.setData(list);
        json.setSuccess(true);
        this.writeJson(response,json);
    }

	/** 
	 * @Description: save 
	 * @Param: [request, response, session] 
	 * @return: void 
	 * @Author: anxingtao
	 * @Date: 2020-9-22 22:51 
	 */
	@RequestMapping(value = "/saveOrUpdate", method = RequestMethod.POST)
	public void save(@RequestHeader HttpHeaders headers, @RequestBody PageData pd, HttpServletResponse response) throws IOException  {
		Json json = new Json();
		System.out.println(pd.toString());
		//处理数据权限
		String  token = headers.get("access-token").get(0);
		System.out.println("findUserInfo###########TOKEN:"+token);
		String user_id = JwtUtils.validateJWT(token).getClaims().getId().split(":")[0];
		String organize_id = JwtUtils.validateJWT(token).getClaims().getId().split(":")[1];
		String time = DateTimeUtil.getDateTimeStr();
        if(Verify.verifyIsNotNull(pd.get("id"))){
            pd.put("update_time", time);
            pd.put("update_user",user_id);
            int num = mytreeService.update(pd);
            if(num==1){
            }
            json.setSuccess(true);
            json.setMsg("操作成功。");
		}else{
            pd.put("parent_id", pd.get("parent_id"));
            //主键id
            String id = GuidUtil.getUuid();
            pd.put("id", id);
            pd.put("create_time", time);
            pd.put("status","1");
            //处理数据权限
            pd.put("create_user",user_id);
            pd.put("create_organize",organize_id);

            int num = mytreeService.save(pd);
            if(num==1){
            }
            json.setSuccess(true);
            json.setMsg("操作成功。");
		}
		this.writeJson(response,json);
	}


	/**
	 * @Description: del 
	 * @Param: [request, response] 
	 * @return: void 
	 * @Author: anxingtao
	 * @Date: 2020-9-22 22:51 
	 */
	@RequestMapping(value = "/del", method = RequestMethod.GET)
	public void del(@RequestHeader HttpHeaders headers, @RequestParam String ids, HttpServletResponse response) throws IOException  {
		PageData pd = new PageData();
		String[] del_ids = ids.split(",");
		mytreeService.del(del_ids);
		Json json = new Json();
		json.setSuccess(true);
		json.setMsg("操作成功。");
		this.writeJson(response,json);
	}

}

qingfeng-interface/src/main/resources/templates/gencode/TemplateApi.js.ftl
import request from '@/utils/request'

export function getListPage (parameter) {
  return request({
    url: '/${tablePd.mod_name}/${tablePd.bus_name}/findListPage',
    method: 'post',
    data: parameter
  })
}
  
export function saveOrUpdate (parameter) {
  console.log(parameter);
  return request({
    url: '/${tablePd.mod_name}/${tablePd.bus_name}/saveOrUpdate',
    method: 'post',
    data: parameter
  })
}

export function delData (ids) {
  console.log(ids);
  return request({
    url: '/${tablePd.mod_name}/${tablePd.bus_name}/del?ids='+ids,
    method: 'get',
    headers: {
      'Content-Type': 'application/json;charset=UTF-8',
    }
  })
}

export function findList (parameter) {
  return request({
    url: '/${tablePd.mod_name}/${tablePd.bus_name}/findList',
    method: 'post',
    data: parameter
  })
}

qingfeng-interface/src/main/resources/templates/gencode/TemplateEdit.vue.ftl
<template>
  <a-form-model
    ref="ruleForm"
    :model="form"
    :rules="rules"
    :label-col="labelCol"
    :wrapper-col="wrapperCol"
  >
   <#if tablePd.temp_type == '1'>
    <a-form-model-item ref="parent_name" label="父级名称" prop="parent_name">
      <a-input disabled v-model="form.parent_name" />
    </a-form-model-item>
    </#if>
<#list fieldList as obj>
    <#if obj.field_operat == 'Y'>
        <#if obj.show_type == '1'>
	<a-form-model-item ref="${obj.field_name}" label="${obj.field_comment}" prop="${obj.field_name}">
	    <a-input
		v-model="form.${obj.field_name}"
		@blur="
		  () => {
		    ${'$'}refs.${obj.field_name}.onFieldBlur();
		  }
		"
	      />
	</a-form-model-item>
	</#if>
	<#if obj.show_type == '2'>
	<a-form-model-item label="${obj.field_comment}" prop="${obj.field_name}">
		<a-input v-model="form.${obj.field_name}" type="textarea" />
	</a-form-model-item>
	</#if>
	<#if obj.show_type == '3'>
	<a-form-model-item ref="${obj.field_name}" label="${obj.field_comment}" prop="${obj.field_name}">
        <a-select v-model="form.${obj.field_name}" placeholder="请选择${obj.field_comment}">
            <a-select-option v-for="(item, index) in ${obj.field_name}_data" :value="item.id"> {{item.name}} </a-select-option>
        </a-select>
    </a-form-model-item>
	</#if>
	<#if obj.show_type == '4'>
    <a-form-model-item ref="${obj.field_name}" label="${obj.field_comment}" prop="${obj.field_name}">
	    <a-radio-group v-model="form.${obj.field_name}">
	        <a-radio v-for="(item, index) in ${obj.field_name}_data" :value="item.id">{{item.name}} </a-radio>
	    </a-radio-group>
    </a-form-model-item>
	</#if>
	<#if obj.show_type == '5'>
    <a-form-model-item ref="${obj.field_name}" label="${obj.field_comment}" prop="${obj.field_name}">
	    <a-checkbox-group v-model="form.${obj.field_name}">
		    <a-checkbox v-for="(item, index) in ${obj.field_name}_data" :value="item.id">{{item.name}}</a-checkbox>
	    </a-checkbox-group>
    </a-form-model-item>
	</#if>
	<#if obj.show_type == '6'>
    <a-form-model-item ref="${obj.field_name}" label="${obj.field_comment}" prop="${obj.field_name}">
	    <rich-text :text="form.${obj.field_name}" @editorChange="editorChange" />
    </a-form-model-item>
	</#if>
	<#if obj.show_type == '8'>
    <a-form-model-item ref="${obj.field_name}" label="${obj.field_comment}" prop="${obj.field_name}">
        <a-upload
            name="file"
            :multiple="true"
            :show-upload-list="false"
            :customRequest="upload${obj.field_name}File"
            :loading="uploading"
        >
        <a-button> <a-icon type="upload" /> Upload </a-button>
        </a-upload>
        <div v-for="(item, index) in ${obj.field_name}FileList" :style="{ lineHeight: '30px' }">
            <a @click="download${obj.field_name}File(item)"><a-icon type="link" />{{ item.name }}</a>
            <a @click="del${obj.field_name}File(item)" :style="{ paddingLeft: '10px', color: 'red' }"><a-icon type="delete"/></a>
        </div>
    </a-form-model-item>
	</#if>
</#if>
</#list>
  </a-form-model>
</template>
<script>
import { saveOrUpdate } from "@/api/${tablePd.mod_name}/${tablePd.bus_name}";
import { findDictionaryList } from "@/api/system/dictionary";
<#list fieldList as obj>
<#if obj.field_operat == 'Y'>
<#if obj.show_type == '6'>
import RichText from "@/components/Common/RichText";
</#if>
<#if obj.show_type == '8'>
import { upload } from "@/api/common/upload";
</#if>
</#if>
</#list>
export default {
  // 声明当前子组件接收父组件传递的属性
  props: {
    record: {
      type: Object,
      default: null,
    },
  },
  data() {
    return {
      labelCol: { span: 4 },
      wrapperCol: { span: 14 },
      other: "",
      mybol: false,
      headers: {
        authorization: "authorization-text",
      },
      uploading: false,
      form: {
        id: "",
<#list fieldList as obj>
    <#if obj.field_operat == 'Y'>
    <#if obj.show_type == '5'>
	    ${obj.field_name}:[],
    </#if>
    <#if obj.show_type != '5'>
        ${obj.field_name}:"",
    </#if>
    </#if>
</#list>
      },
  <#list fieldList as obj>
      <#if obj.show_type == '3' || obj.show_type == '4' || obj.show_type == '5'>
          ${obj.field_name}_data:[],
      </#if>
      <#if obj.show_type == '8'>
          ${obj.field_name}FileList: [],
      </#if>
  </#list>
      rules: {
      <#list fieldList as obj>
	    <#if obj.field_operat == 'Y' && obj.verify_rule=='required'>
        ${obj.field_name}: [
            { required: true, message: "必填项不能为空", trigger: "blur" },
            { min: 0, max: 120, message: "长度不得大于120个字符", trigger: "blur" },
        ],
	    </#if>
	</#list>
      },
    }
  },
  components: {
<#list fieldList as obj>
    <#if obj.field_operat == 'Y'>
        <#if obj.show_type == '6'>
    RichText
        </#if>
    </#if>
</#list>
  },
  mounted() {
    if(this.record.id != undefined) {
      this.form = this.record;
    }
<#if tablePd.temp_type == '1'>
    this.form.parent_id = this.record.parent_id;
    this.form.parent_name = this.record.parent_name;
    this.${'$'}forceUpdate();
</#if>
<#list fieldList as obj>
<#if obj.show_type == '8'>
    if (this.record.introFileList != undefined) {
        this.${obj.field_name}FileList = this.record.${obj.field_name}FileList
    }
</#if>
</#list>
    this.initData();
  },
  methods: {
<#list fieldList as obj>
    <#if obj.show_type == '8'>
    del${obj.field_name}File(record,fileList) {
        let index = this.${obj.field_name}FileList.findIndex((ele) => {
            return ele.id === record.id;
        })
      //假设没有找到
      if (index === -1) {
          return console.log("删除失败");
      }
      //删除元素
      this.${obj.field_name}FileList.splice(index, 1);
      this.form.${obj.field_name} = this.${obj.field_name}FileList.map((map) => {
        return map.id;
      })
    },
    download${obj.field_name}File(record) {
      window.location.href =
              process.env.VUE_APP_API_URL +
              "/common/upload/downloadFile?name=" +
              record.name +
              "&file_path=" +
              record.file_path;
    },
    // 上传文件
    upload${obj.field_name}File(file) {
      this.uploading = true;
      const formData = new FormData();
      formData.append("file", file.file);
      upload(formData).then(
              (res) => {
          if (res.success) {
          this.${obj.field_name}FileList.push(res.data);
          this.uploading = false;
          this.form.${obj.field_name} = this.${obj.field_name}FileList.map((map) => {
              return map.id;
      })
      }
    },
      (err) => {
          this.uploading = false;
      })
   },
    </#if>
</#list>
  <#list fieldList as obj>
    <#if obj.field_operat == 'Y'>
        <#if obj.show_type == '6'>
    editorChange: function (html) {
      this.content = html;
    },
    	</#if>
</#if>
</#list>
    resetForm() {
      this.${'$'}refs.ruleForm.resetFields();
    },
    onOk() {
      console.log(this.mybol);
      this.${'$'}refs.ruleForm.validate((valid) => {
        if (valid) {
        <#list fieldList as obj>
        <#if obj.field_operat == 'Y'>
        <#if obj.show_type == '5'>
            this.form.${obj.field_name} = this.form.${obj.field_name}.join(',');
        </#if>
        </#if>
        </#list>
           saveOrUpdate(this.form).then((response) => {
                console.log(response)
           })
          this.mybol = true;
          return true;
        } else {
          this.mybol = false;
          console.log("error submit!!");
          return false;
        }
        })
        return new Promise((resolve) => {
            resolve(this.mybol)
        })
    },
    onCancel() {
      console.log("监听了 modal cancel 事件");
      return new Promise((resolve) => {
        resolve(true)
      })
    },
    initData(){
<#list fieldList as obj>
    <#if obj.show_type == '3' || obj.show_type == '4' || obj.show_type == '5'>
    <#if obj.option_content?contains(";")>
        const options = [
            <#list obj.option_content?split(";") as name>
                <#assign param = name?split("/")>
                { id: '${param[0]}', name: '${param[1]}' },
            </#list>
        ];
        this.${obj.field_name}_data = options;
    </#if>
    <#if !obj.option_content?contains(";")>
        findDictionaryList({parent_code:'${obj.option_content}'}).then((response) => {
            this.${obj.field_name}_data = response.data;
        })
    </#if>

    </#if>
    <#if obj.show_type != '5'>
        <#if obj.default_value??>
            this.form.${obj.field_name} = '${obj.default_value!''}';
        </#if>
    </#if>
    <#if obj.show_type == '5'>
        <#if obj.default_value??>
            this.form.${obj.field_name} = ['${obj.default_value!''}'];
        </#if>
    </#if>
</#list>
    },
  },
};
</script>

qingfeng-interface/src/main/resources/templates/gencode/TemplateMenuSql.sql.ftl
<#list menuList as obj>
<#if obj.type == 'menu'>
-- 生成菜单
</#if>
<#if obj.type == 'button'>
<#if obj.code == 'add'>
-- 生成添加按钮
</#if>
<#if obj.code == 'edit'>
-- 生成编辑按钮
</#if>
<#if obj.code == 'del'>
-- 生成删除按钮
</#if>
<#if obj.code == 'info'>
-- 生成详情按钮
</#if>
</#if>
insert into system_menu (id,type,name,path,component,title,keepAlive,permission,parent_id,status,order_by,remark,create_time,create_user,create_organize)
	values
	('${obj.id}','${obj.type}','${obj.title}','${obj.path}','${obj.component}','${obj.title}','${obj.keepAlive}','${obj.permission}','${obj.parent_id}','${obj.status}','${obj.order_by}','${obj.remark}','${obj.create_time}','${obj.create_user}','${obj.create_organize}');
</#list>